# Generated by Django 2.2.3 on 2019-12-11 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='coordinate_mobile',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='nomatch', message='فقط ۱۱ عدد میتوانید وارد کنید!', regex='^[0-9]{11}$')], verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coordinate_phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='nomatch', message='فقط ۱۱ عدد میتوانید وارد کنید!', regex='^[0-9]{11}$')], verbose_name='تلفن ثابت'),
        ),
    ]
