# Generated by Django 2.2.3 on 2019-12-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20191211_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
